### ISSUE TITLE
 Ns.update errors

### ISSUE THREAD

**Issue by sylwesterdigital** [zalo/ThreeOverlay#1]
I have built and added the main.js to my index.html, testing in Brave  - it creates these errors: 

``
main.js:48 Uncaught 
TypeError: Cannot read properties of undefined (reading '_setScroll')
    at Ns.update (main.js:48:20)
    at oe (three.module.js:29278:36)
    at s (three.module.js:13408:3)
main.js:61 Uncaught 
TypeError: Cannot read properties of null (reading 'appendChild')
    at Ns.display (main.js:61:46)
    at main.js:14:18
World.js:149 Uncaught (in promise) 
TypeError: Cannot read properties of null (reading 'style')
    at Ti._setScroll (World.js:149:31)
    at Ti._onWindowResize (World.js:216:14)
    at new Ti (World.js:77:14)
    at Ns.deferredConstructor (main.js:22:22)
    at new Ns (main.js:18:14)
    at main.js:65:12
gallery.js:11 
``
<img width="654" alt="Screenshot 2024-06-05 at 12 31 17" src="https://github.com/zalo/ThreeOverlay/assets/27820237/e2b12133-f097-4150-b2b5-fc163a6c83f1">

**Comment by zalo** [comment]
Ah sorry, this isn’t fully self-contained yet, but you’d also need to add the appbody-bg and appbody-fg elements from the HTML to your index.html.  

Also it’s perhaps better to run without building if possible to preserve variable names 🤔
